/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.24.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./ShitStrap.types";
import * as _1 from "./ShitStrap.client";
import * as _2 from "./ShitStrap.message-composer";
import * as _3 from "./Cw20Base.types";
import * as _4 from "./Cw20Base.client";
import * as _5 from "./Cw20Base.message-composer";
export namespace contracts {
  export const ShitStrap = { ..._0,
    ..._1,
    ..._2
  };
  export const Cw20Base = { ..._3,
    ..._4,
    ..._5
  };
}