/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.24.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./ShitStrap.types";
import * as _1 from "./ShitStrap.client";
import * as _2 from "./ShitStrap.message-composer";
import * as _3 from "./ShitStrap.react-query";
import * as _4 from "./Cw20Base.types";
import * as _5 from "./Cw20Base.client";
import * as _6 from "./Cw20Base.message-composer";
import * as _7 from "./Cw20Base.react-query";
import * as _8 from "./ShitStrapFactory.types";
import * as _9 from "./ShitStrapFactory.client";
import * as _10 from "./ShitStrapFactory.message-composer";
import * as _11 from "./ShitStrapFactory.react-query";
export namespace contracts {
  export const ShitStrap = { ..._0,
    ..._1,
    ..._2,
    ..._3
  };
  export const Cw20Base = { ..._4,
    ..._5,
    ..._6,
    ..._7
  };
  export const ShitStrapFactory = { ..._8,
    ..._9,
    ..._10,
    ..._11
  };
}